### ISSUE TITLE
DeprecationWarning crypto.DEFAULT_ENCODING, crypto.createCredentials, crypto.Credentials

### ISSUE THREAD

**Issue by PaulMest** [aleung/node-anyid#12] opened 2019-07-29 10:34 UTC
Nice library! On Node v10, we are getting the following warnings when we import `anyid`.
```
[DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
[DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
[DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
```

**Comment by frejonb** [comment] 2019-08-25 20:52
@PaulMest  The problem is some calls are deprecated https://github.com/nodejs/node/issues/20793. Fortunately the one needed in this module is not, so the warning is fixed in https://github.com/aleung/node-anyid/pull/13

**Closed as completed** 2019-08-26 15:30 UTC
